#!/bin/bash
# Hammer Mei — memory sync script
# Usage: memory-sync.sh --init [harness] | --pull | --push
#
# Invoked by Claude Code hooks (settings/claude/settings.json):
#   SessionStart     → --init claude-code  (once per session: env dir + visited.md)
#   UserPromptSubmit → --pull              (pull latest memory from remote)
#   Stop             → --push             (commit + push local memory changes)
#
# ASSISTANT_SETUP_REPO: path to tamago repo (default: ~/.tamago)
# LAOMEI_MEMORY_SYNC:   set to 0 to disable all sync (offline/emergency)
#
# Profile repo discovery (priority order):
#   1. .tamago/machine.env  (written by `tamago install`, shell-sourceable KEY=VALUE)
#   2. ~/.tamago/machine.env  (global agent install, no project-level config)
#   If none found the project has no tamago agent — exit silently.
#
# Multi-agent support:
#   AGENT_NAMES in machine.env holds a space-separated list of all installed agents.
#   memory-sync.sh loops over them for --init (env dir + visited.md per agent).
#   --pull and --push operate on the whole profile repo — no per-agent loop needed.
#   Backward compat: falls back to single AGENT_NAME when AGENT_NAMES is absent.

REPO="${ASSISTANT_SETUP_REPO:-$HOME/.tamago}"
MEMORY_PATH="agents/memory"

# ─── Config discovery (2-step, first match wins) ─────────────────────────
# Hooks run with CWD = project dir, so all relative paths are project-scoped.
# 1. Project-scoped machine.env — generated by `tamago install`, shell-sourceable
PROJECT_ENV="$PWD/.tamago/machine.env"
if [ -f "$PROJECT_ENV" ]; then
  # shellcheck source=/dev/null
  . "$PROJECT_ENV"
fi

# 2. Global fallback: ~/.tamago/machine.env (for globally-installed agents)
if [ -z "$PROFILE_REPO" ]; then
  GLOBAL_ENV="$HOME/.tamago/machine.env"
  if [ -f "$GLOBAL_ENV" ]; then
    # shellcheck source=/dev/null
    . "$GLOBAL_ENV"
  fi
fi

# No profile configured — not a tamago project, skip silently.
if [ -z "$PROFILE_REPO" ]; then
    exit 0
fi
MEMORY_REPO="$PROFILE_REPO"

# Sync disabled — env var (LAOMEI_MEMORY_SYNC=0) or tamago.conf (MEMORY_SYNC=0)
if [ "${LAOMEI_MEMORY_SYNC:-1}" = "0" ] || [ "${MEMORY_SYNC:-1}" = "0" ]; then
    exit 0
fi

case "$1" in
  --init)
    HOSTNAME=$(hostname)

    # Determine the list of agents to init.
    # Priority: AGENT_NAMES (multi-agent list) > AGENT_NAME (legacy single) > settings.json.
    if [ -n "$AGENT_NAMES" ]; then
      INIT_AGENTS="$AGENT_NAMES"
    elif [ -n "$AGENT_NAME" ]; then
      INIT_AGENTS="$AGENT_NAME"
    else
      AGENT_SETTINGS="$MEMORY_REPO/settings/claude/settings.json"
      if [ -f "$AGENT_SETTINGS" ]; then
        INIT_AGENTS=$(python3 -c "
import json, sys
print(json.load(open(sys.argv[1])).get('agent', 'hammer.mei'))
" "$AGENT_SETTINGS" 2>/dev/null || echo "hammer.mei")
      else
        INIT_AGENTS="hammer.mei"
      fi
    fi

    # 2. Harness — use explicit argument if provided, otherwise best-effort detect
    if [ -n "$2" ]; then
      HARNESS="$2"
    elif [ "${CLAUDECODE:-0}" = "1" ]; then
      HARNESS="claude-code"
    elif [ "${OPENCODE:-0}" = "1" ] || echo "$PATH" | grep -q "/.opencode/bin"; then
      HARNESS="opencode"
    else
      HARNESS="unknown"
    fi

    # 3. Detect model (best effort — check profile settings first, then tamago common)
    PROFILE_SETTINGS="$MEMORY_REPO/settings/claude/settings.json"
    COMMON_SETTINGS="$REPO/settings/claude/settings.json"
    if [ -f "$PROFILE_SETTINGS" ]; then
      MODEL=$(python3 -c "
import json, sys
print(json.load(open(sys.argv[1])).get('defaultModel', 'unknown'))
" "$PROFILE_SETTINGS" 2>/dev/null || echo "unknown")
    elif [ -f "$COMMON_SETTINGS" ]; then
      MODEL=$(python3 -c "
import json, sys
print(json.load(open(sys.argv[1])).get('defaultModel', 'unknown'))
" "$COMMON_SETTINGS" 2>/dev/null || echo "unknown")
    else
      MODEL="unknown"
    fi

    # 4. Init env dir + visited.md for each agent; commit once at the end.
    NEEDS_COMMIT=false
    for AGENT in $INIT_AGENTS; do
      ENV_DIR="$MEMORY_REPO/$MEMORY_PATH/$AGENT/env-$HOSTNAME"

      # Ensure env dir exists
      if [ ! -d "$ENV_DIR" ]; then
        mkdir -p "$ENV_DIR"
        printf "# Environment Memory — %s\n\n首次見面：%s\n" "$HOSTNAME" "$(date +%Y-%m-%d)" > "$ENV_DIR/MEMORY.md"
        NEEDS_COMMIT=true
      fi

      # Append to visited.md only if harness+model changed
      VISITED="$ENV_DIR/visited.md"
      LAST=$(tail -1 "$VISITED" 2>/dev/null || echo "")
      if ! echo "$LAST" | grep -q "| $HARNESS | $MODEL"; then
        if [ ! -f "$VISITED" ]; then
          printf "# Visited Log — %s\n\nRecords when harness or model changes. Append-only.\nFormat: \`- {YYYY-MM-DD} | {harness} | {model}\`\n\n" "$HOSTNAME" > "$VISITED"
        fi
        printf -- "- %s | %s | %s\n" "$(date +%Y-%m-%d)" "$HARNESS" "$MODEL" >> "$VISITED"
        NEEDS_COMMIT=true
      fi
    done

    # 5. Commit + push immediately so UserPromptSubmit pull sees a clean working tree
    if [ "$NEEDS_COMMIT" = true ]; then
      cd "$MEMORY_REPO" && \
        git add "$MEMORY_PATH" && \
        git commit -m "auto: session init footprint" --quiet && \
        (git pull --rebase --quiet && git push --quiet) 2>/dev/null || true
    fi
    ;;

  --pull)
    # Skip if no remote is configured
    git -C "$MEMORY_REPO" remote get-url origin &>/dev/null || exit 0
    # Pull latest memory; surface warning to both Claude context and CLI on failure
    if ! (cd "$MEMORY_REPO" && timeout 5 git pull --rebase --quiet) 2>/dev/null; then
      echo "Memory sync warning: git pull failed — you may be out of sync with other 分身. Consider running 'git pull --rebase' in $MEMORY_REPO manually."
    fi
    ;;

  --push)
    cd "$MEMORY_REPO" || exit 0

    # Nothing to sync
    git diff --quiet "$MEMORY_PATH" 2>/dev/null && exit 0

    # Commit local changes
    git add "$MEMORY_PATH" && \
      git commit -m "auto: sync memory on turn end" --quiet || exit 0

    # Skip push if no remote is configured (commit is kept locally)
    git remote get-url origin &>/dev/null || exit 0

    # Pull --rebase then push; surface systemMessage to user on failure
    if ! (git pull --rebase --quiet && git push --quiet) 2>/dev/null; then
      printf '{"systemMessage": "⚠️ Memory sync failed: push rejected. Run: cd %s && git pull --rebase && git push"}\n' "$MEMORY_REPO"
    fi
    ;;

  *)
    echo "Usage: $0 --init [harness] | --pull | --push" >&2
    exit 1
    ;;
esac
